//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchLoader.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EncodingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncodingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchLoader.Services.EncodingResource", typeof(EncodingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01101.
        /// </summary>
        internal static string bases_Asterisk {
            get {
                return ResourceManager.GetString("bases_Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00011.
        /// </summary>
        internal static string bases_CapitalA {
            get {
                return ResourceManager.GetString("bases_CapitalA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00101.
        /// </summary>
        internal static string bases_CapitalC {
            get {
                return ResourceManager.GetString("bases_CapitalC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00111.
        /// </summary>
        internal static string bases_CapitalG {
            get {
                return ResourceManager.GetString("bases_CapitalG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01011.
        /// </summary>
        internal static string bases_CapitalN {
            get {
                return ResourceManager.GetString("bases_CapitalN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01001.
        /// </summary>
        internal static string bases_CapitalT {
            get {
                return ResourceManager.GetString("bases_CapitalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00010.
        /// </summary>
        internal static string bases_Comma {
            get {
                return ResourceManager.GetString("bases_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00001.
        /// </summary>
        internal static string bases_Dot {
            get {
                return ResourceManager.GetString("bases_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00100.
        /// </summary>
        internal static string bases_SmallA {
            get {
                return ResourceManager.GetString("bases_SmallA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00110.
        /// </summary>
        internal static string bases_SmallC {
            get {
                return ResourceManager.GetString("bases_SmallC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01000.
        /// </summary>
        internal static string bases_SmallG {
            get {
                return ResourceManager.GetString("bases_SmallG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01100.
        /// </summary>
        internal static string bases_SmallN {
            get {
                return ResourceManager.GetString("bases_SmallN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01010.
        /// </summary>
        internal static string bases_SmallT {
            get {
                return ResourceManager.GetString("bases_SmallT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        internal static string refNuc_A {
            get {
                return ResourceManager.GetString("refNuc_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010.
        /// </summary>
        internal static string refNuc_C {
            get {
                return ResourceManager.GetString("refNuc_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011.
        /// </summary>
        internal static string refNuc_G {
            get {
                return ResourceManager.GetString("refNuc_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string refNuc_T {
            get {
                return ResourceManager.GetString("refNuc_T", resourceCulture);
            }
        }
    }
}
